name: Buginforme
description: Dar su opinión sobre este complementoBugo pregunta
labels: ["bug"]
assignees:
  - ybw0014
body:
  - type: markdown
    attributes:
      value: |
        ## bienvenido a SlimefunGuguProject Bug rastreador
        estás dando retroalimentación NotEnoughAddons versión china Bug。
        Se recomienda leer primero.[Este artículo](https://slimefun-wiki.guizhanss.cn/How-to-report-bugs)Aprende cómo reportar correctamenteBug。

        <strong><i>Debes rellenar los campos marcados con un asterisco（*）elemento de formulario</i></strong>

  - type: checkboxes
    id: checklist
    attributes:
      label: comprobar artículos
      description: Antes de informar, debe confirmar
      options:
        - label: Estás utilizando la versión descargada del sitio de compilación. (https://builds.guizhanss.net)
          required: true
        - label: Ha verificado la suma de verificación del archivo descargado para confirmar que el archivo se ha descargado por completo. (Aún no lanzado)
          required: false
        - label: No ha realizado ningún cambio en el contenido del archivo descargado.
          required: true
        - label: no lo tienes instalado`CS-CoreLib`
          required: true
        - label: ya has buscado[Lista de problemas conocidos](https://github.com/SlimefunGuguProject/NotEnoughAddons/issues)，y no se encontraron problemas similares
          required: true

  - type: textarea
    id: description
    attributes:
      label: Descripción del problema
      description: |
        Describe detalladamente el problema que deseas reportar.
        Proporcionar información detallada nos permite resolver problemas más rápido
      placeholder: solo di"El ____ no funciona"Los desarrolladores no tienen forma de localizar el problema.。
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Pasos de reproducción
      description: |
        Describa en detalle cómo reproducir el problema.
        Si hay un video, proporcione el enlace del video aquí.
      placeholder: |
        1. xxx
        2. xxx
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: comportamiento esperado
      description: |
        ¿Qué crees que debería pasar?
        A veces el problema es que no entendiste una característica.。
    validations:
      required: true

  - type: input
    id: server-log
    attributes:
      label: Registro del servidor
      description: |
        Compruebe si el registro del servidor contiene algún error. Si es así, súbelo a [https://paste.guizhanss.net/](https://paste.guizhanss.net/) y rellena el enlace aquí。
        **No pegue registros directamente aquí**
      placeholder: https://paste.guizhanss.net/...
    validations:
      required: false

  - type: input
    id: error-report
    attributes:
      label: informe de errores
      description: |
        Si los registros del servidor mencionan`/plugins/Slimefun/error-reports`archivos en (es decir, informes de errores)
        Por favor suba a [https://paste.guizhanss.net/](https://paste.guizhanss.net/) y rellena el enlace aquí。
        **No pegue informes de errores directamente aquí**
      placeholder: https://paste.guizhanss.net/...
    validations:
      required: false

  - type: dropdown
    id: server-software
    attributes:
      label: software de servidor
      description: Por favor seleccione el software utilizado por su servidor
      options:
        - Spigot
        - Paper
        - Purpur
        - Airplane
        - otro (Por favor escríbalo en la descripción del problema.)
    validations:
      required: true

  - type: dropdown
    id: minecraft-version
    attributes:
      label: Minecraft Versión
      description: Por favor elige tu Minecraft Versión
      options:
        - 1.18.x
        - 1.17.x
        - 1.16.x
        - Este complemento no es compatible con versiones anteriores
    validations:
      required: true

  - type: checkboxes
    id: cscorelib-version
    attributes:
      label: CS-CoreLib Versión
      description: |
        de2021Año1luna30De，Slimefuny ya no es necesario instalar los complementos que lo acompañan.CS-CoreLib。
        reservarCS-CoreLibpuede causar algunos problemas desconocidos。
      options:
        - label: no lo tengo instaladoCS-CoreLib
          required: true

  - type: textarea
    id: slimefun-version
    attributes:
      label: SlimefunVersión
      description: |
        Por favor completeSlimefunVersión
        (Por ejemplo v4.9-canary-08120db)
        Si tiene derechos de administrador, se recomienda ejecutar`/sf versions`comando, captura de pantalla y cargue el resultado del comando aquí**Todo el contenido**。
    validations:
      required: true

  - type: input
    id: version-plugin
    attributes:
      label: Versión del complemento
      description: |
        Por favor complete la versión del complemento
        Solo completaBuildLa versión digital estará disponible más adelante.
        (`Build 7 zh-CN(ybw0014) (git 9ef7fee)`Solo completa`7`Eso es todo)
    validations:
      required: true